env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'semi': off,
    'react/react-in-jsx-scope': off,
    'object-curly-spacing': off,
    'max-len': off,
    'valid-jsdoc': off,
    'require-jsdoc': off,
  }
settings:
  react:
    version: detect
